#!/usr/bin/env python3
"""Collect every L["..."] phrase in the addon and write the CurseForge import file.

    python tools/extract_locale_phrases.py            # regenerate locale_phrases.lua
    python tools/extract_locale_phrases.py --check    # lint only, no write

DelveGuide_Locale.lua defines L as a table whose __index returns the key, so the
English text IS the key and the phrase list is simply every string literal the
addon indexes L with. That makes the list mechanically derivable -- which is the
point: nobody has to remember to add a phrase to a second file.

The output is the format CurseForge's localization platform imports (one
`L["phrase"] = true` per line); its exporter then hands the packager back
`L["phrase"] = "translation"` lines for each locale.

--check exits 1 if any `L[` in the scanned files is followed by something other
than a string literal. `L[someVariable]` cannot be extracted, cannot be
translated and cannot be spotted by reading the phrase list -- it can only be
caught here.

Only the addon's root .lua files are scanned; tools/locale_phrases.lua is
generated FROM them and everything under libs/ belongs to somebody else.
"""

import argparse
import glob
import os
import re
import sys

REPO = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), os.pardir))
OUT_REL = os.path.join("tools", "locale_phrases.lua")

# `L` as a whole identifier, so STATE_LABEL[state] is not a hit, followed by a
# single- or double-quoted Lua string. The alternation inside each quote style
# is the standard "not a quote, or any escaped character" pair, which is what
# makes L["say \"hi\""] come out in one piece.
PHRASE_RE = re.compile(
    r'(?<![A-Za-z0-9_])L\[\s*(?:"((?:[^"\\]|\\.)*)"|\'((?:[^\'\\]|\\.)*)\')\s*\]'
)

# The same `L[`, NOT followed by a quote.
NON_LITERAL_RE = re.compile(r'(?<![A-Za-z0-9_])L\[\s*(?![\'"])')

BLOCK_COMMENT_RE = re.compile(r'--\[(=*)\[.*?\]\1\]', re.S)

_UNESCAPE = {'\\': '\\', '"': '"', "'": "'", 'n': '\n', 't': '\t', 'r': '\r', 'a': '\a', 'b': '\b'}


def lua_files():
    """The addon's own .lua files, repo root only, sorted for stable output."""
    return sorted(os.path.basename(p) for p in glob.glob(os.path.join(REPO, "*.lua")))


def strip_comments(text):
    """Blank out block comments and whole-line `--` comments.

    Only WHOLE-LINE comments go: a trailing `--` cannot be told from the `--`
    inside a display string ("|r -- click to unlock") without a real Lua lexer,
    and dropping one of those would silently lose a phrase. Whole-line comments
    are what actually matter here -- DelveGuide_Locale.lua's header documents
    the policy with example L["..."] lines that must not become phrases.
    """
    text = BLOCK_COMMENT_RE.sub(lambda m: "\n" * m.group(0).count("\n"), text)
    out = []
    for line in text.split("\n"):
        out.append("" if line.lstrip().startswith("--") else line)
    return "\n".join(out)


def unescape(raw):
    """Lua source form -> the actual string value, so 'x' and "x" dedupe."""
    out, i = [], 0
    while i < len(raw):
        c = raw[i]
        if c == "\\" and i + 1 < len(raw):
            nxt = raw[i + 1]
            out.append(_UNESCAPE.get(nxt, "\\" + nxt))
            i += 2
        else:
            out.append(c)
            i += 1
    return "".join(out)


def escape(value):
    """The actual string value -> a double-quoted Lua literal's contents."""
    return (value.replace("\\", "\\\\")
                 .replace('"', '\\"')
                 .replace("\n", "\\n")
                 .replace("\r", "\\r")
                 .replace("\t", "\\t"))


def read(rel):
    with open(os.path.join(REPO, rel), encoding="utf-8") as fh:
        return fh.read()


def extract(rels):
    """Every distinct phrase across the given files, sorted."""
    phrases = set()
    for rel in rels:
        for m in PHRASE_RE.finditer(strip_comments(read(rel))):
            raw = m.group(1) if m.group(1) is not None else m.group(2)
            phrases.add(unescape(raw))
    return sorted(phrases)


def find_non_literals(rels):
    """(file, line number, line) for every `L[` that is not indexed by a literal."""
    bad = []
    for rel in rels:
        for n, line in enumerate(strip_comments(read(rel)).split("\n"), 1):
            if NON_LITERAL_RE.search(line):
                bad.append((rel, n, line.strip()))
    return bad


def render(phrases):
    return (
        "-- GENERATED by tools/extract_locale_phrases.py -- do not edit by hand.\n"
        "-- %d phrases, from every L[\"...\"] literal in the addon's root .lua files.\n"
        "-- Import format for CurseForge localization (lua_additive_table).\n"
        % len(phrases)
        + "".join('L["%s"] = true\n' % escape(p) for p in phrases)
    )


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="lint for L[variable] and write nothing; exit 1 on a hit")
    args = ap.parse_args(argv)

    rels = lua_files()
    bad = find_non_literals(rels)
    for rel, n, line in bad:
        print("%s:%d: L[] indexed by something other than a string literal: %s"
              % (rel, n, line))

    if args.check:
        if bad:
            print("FAIL: %d non-literal L[] use(s)" % len(bad))
            return 1
        print("OK: every L[] in %d file(s) is indexed by a string literal" % len(rels))
        return 0

    if bad:
        return 1

    phrases = extract(rels)
    with open(os.path.join(REPO, OUT_REL), "w", encoding="utf-8", newline="\n") as fh:
        fh.write(render(phrases))
    print("wrote %s -- %d phrases from %d file(s)" % (OUT_REL, len(phrases), len(rels)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
